config/routes.rb
Danberk::Application.routes.draw do
  get "users/new"

  root :to => 'pages#home'
  match '/contact', :to => 'pages#contact'
  match '/about', :to => 'pages#about'
  match '/projects', :to => 'pages#projects'
  match '/signup', :to => 'users#new'

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :email
end

# == Schema Information
#
# Table name: users
#
#  id         :integer         not null, primary key
#  name       :string(255)
#  email      :string(255)
#  created_at :datetime
#  updated_at :datetime
#

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def home
    @title = "Home"
  end

  def contact
    @title = "Contact"
  end
  
  def about
    @title = "About"
  end
  
  def projects
    @title = "Projects"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @title = "Sign up"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  
  # Return a title on a per-page basis
  def title
    base_title = "DB"
    if @title.nil?
      base_title
    else
      "#{base_title} | #{@title}"
    end
  end
  
  def logo
    image_tag("logo.png", :alt => "Dan Berk", :class => "logo")
  end
  
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer>
	<nav>
		<ul>
			<li><%= link_to "About", about_path %></li>
			<li><%= link_to "Contact", contact_path %></li>
		</ul>
		<p>© Dan Berk 2012</p>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<header>
	<div class="topstrip"></div>
	<div class="topstripcontainer">
		<%= link_to logo, root_path %>
		<nav class="round">
			<ul>
				<li><%= link_to "Home", root_path %></li>
				<li><%= link_to "Projects", projects_path %></li>
				<li><%= link_to "Sign in", '#' %></li>
			</ul>
		</nav>
	</div>
</header>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://www.html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag 'blueprint/screen', :media => "screen" %>
<%= stylesheet_link_tag 'blueprint/print', :media => "print" %>
<!--[if lt IE 8]>
<%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title><%= title %></title>
		<%= csrf_meta_tag %>
		<%= render 'layouts/stylesheets'%>
	</head>
	<body>
	<div class="container">
		<%= render 'layouts/header' %>
		<section class="round">
			<%= yield %>
		</section>
		<%= render 'layouts/footer' %>	
	</div>
	</body>
</html>

app/views/pages/about.html.erb
		<h1>Welcome to <%= @title %></h1>
		<p>All About Me.</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/home.html.erb
<p>Find me in app/views/pages/home.html.erb</p>

<%= link_to "Sign up", signup_path, :class => "signup_button" %>

app/views/pages/projects.html.erb
Hi!

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>